server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/neurofit_user_db
    username: postgres
    password: nuwaish@1511
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
