server:
  port: 8083

spring:
  application:
    name: recommendation-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/neurofit
      database: neurofit

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
